version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - "./src:/server/src/"
    ports:
      - "3000:4000"
    tty: true
    stdin_open: true
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mynetwork

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
      test: "mysql --password=root --execute 'show databases;'"
      interval: 5s
      timeout: 30s
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
