version: "3"
services:
  unittest-db:
    build:
      context: .
      dockerfile: Dockerfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
      test: "mysql --password=root --execute 'show databases;'"
      interval: 5s
      timeout: 30s
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      TZ: "Asia/Tokyo"
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
